{
 "title": "PostgreSQL Details",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "pgnodes",
    "label": "PGCluster",
    "query": "label_values(up{exp_type='pg'}, job)"
   },
   {
    "name": "backrest_stanza",
    "label": "BackRest Stanza",
    "query": "label_values(ccp_backrest_last_info_backup_runtime_seconds{job=~\"[[pgnodes]]\"}, stanza)"
   }
  ]
 },
 "panels": [
  {
   "title": "[[pgnodes]] - [[backrest_stanza]] Backup Details",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "ccp_backrest_last_incr_backup_time_since_completion_seconds{job=~\"[[pgnodes]]\", stanza=\"[[backrest_stanza]]\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ccp_connection_stats_max_connections{job=~\"[[pgnodes]]\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "ccp_connection_stats_active{job=~\"[[pgnodes]]\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "ccp_connection_stats_idle_in_txn{job=~\"[[pgnodes]]\"}",
     "legendFormat": "IdleTrn"
    },
    {
     "expr": "ccp_connection_stats_idle{job=~\"[[pgnodes]]\"}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(ccp_database_size_bytes{job=~\"[[pgnodes]]\"})",
     "legendFormat": "total size"
    },
    {
     "expr": "ccp_database_size_bytes{job=~\"[[pgnodes]]\"}",
     "legendFormat": "{{dbname}}"
    }
   ]
  },
  {
   "title": "Transactions Per Minute (TPM)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ccp_stat_database_xact_commit{job=~\"[[pgnodes]]\"}[1m])) + sum(irate(ccp_stat_database_xact_rollback{job=~\"[[pgnodes]]\"}[1m]))"
    }
   ]
  },
  {
   "title": "Replication Byte Lag (Primary Only)",
   "type": "graph",
   "description": "Note that replica_port can change if replicas ever detach and re-attach",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ccp_replication_lag_size_bytes{job=~\"[[pgnodes]]\"}",
     "legendFormat": "{{replica_hostname}} ({{replica}}:{{replica_port}})"
    }
   ]
  },
  {
   "title": "Replication Lag Time (Replica Only)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "ccp_replication_lag_replay_time{job=~\"[[pgnodes]]\"}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ccp_stat_database_blks_hit{ job=~\"[[pgnodes]]\"}  / ( ccp_stat_database_blks_hit{job=~\"[[pgnodes]]\"} + ccp_stat_database_blks_read{ job=~\"[[pgnodes]]\"} ) * 100",
     "legendFormat": "{{dbname}}"
    }
   ]
  },
  {
   "title": "Commit vs Rollback",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ccp_stat_database_xact_commit{job=~\"[[pgnodes]]\"}[5m]))",
     "legendFormat": "Commit"
    },
    {
     "expr": "sum(irate(ccp_stat_database_xact_rollback{job=~\"[[pgnodes]]\"}[5m]))",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "title": "CRUD",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ccp_stat_database_tup_fetched{job=~\"[[pgnodes]]\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(irate(ccp_stat_database_tup_inserted{job=~\"[[pgnodes]]\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(irate(ccp_stat_database_tup_updated{job=~\"[[pgnodes]]\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(irate(ccp_stat_database_tup_deleted{job=~\"[[pgnodes]]\"}[5m]))",
     "legendFormat": "Deleted"
    },
    {
     "expr": "sum(irate(ccp_stat_database_tup_returned{job=~\"[[pgnodes]]\"}[5m]))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ccp_locks_count{job=~\"[[pgnodes]]\",mode=\"accessexclusivelock\"})",
     "legendFormat": "accessexclusive"
    },
    {
     "expr": "sum(ccp_locks_count{job=~\"[[pgnodes]]\",mode=\"accesssharelock\"})",
     "legendFormat": "accessshare"
    },
    {
     "expr": "sum(ccp_locks_count{job=~\"[[pgnodes]]\",mode=\"exclusivelock\"})",
     "legendFormat": "exclusive"
    },
    {
     "expr": "sum(ccp_locks_count{job=~\"[[pgnodes]]\",mode=\"rowexclusivelock\"})",
     "legendFormat": "rowexclusive"
    },
    {
     "expr": "sum(ccp_locks_count{job=~\"[[pgnodes]]\",mode=\"rowsharelock\"})",
     "legendFormat": "rowshare"
    },
    {
     "expr": "sum(ccp_locks_count{job=~\"[[pgnodes]]\",mode=\"sharelock\"})",
     "legendFormat": "share"
    },
    {
     "expr": "sum(ccp_locks_count{job=~\"[[pgnodes]]\",mode=\"sharerowexclusivelock\"})",
     "legendFormat": "sharerowexclusive"
    },
    {
     "expr": "sum(ccp_locks_count{job=~\"[[pgnodes]]\",mode=\"shareupdateexclusivelock\"})",
     "legendFormat": "shareupdateexclusive"
    }
   ]
  },
  {
   "title": "Conflicts/DeadLocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ccp_stat_database_deadlocks{job=~\"[[pgnodes]]\"}[5m]))",
     "legendFormat": "Conflicts"
    },
    {
     "expr": "sum(rate(ccp_stat_database_conflicts{job=~\"[[pgnodes]]\"}[5m]))",
     "legendFormat": "DeadLocks"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ccp_stat_bgwriter_buffers_alloc{job=~\"[[pgnodes]]\"}[5m])",
     "legendFormat": "Allocated"
    },
    {
     "expr": "irate(ccp_stat_bgwriter_buffers_backend{job=~\"[[pgnodes]]\"}[5m])",
     "legendFormat": "Backend"
    },
    {
     "expr": "irate(ccp_stat_bgwriter_buffers_backend_fsync{job=~\"[[pgnodes]]\"}[5m])",
     "legendFormat": "FSync"
    },
    {
     "expr": "irate(ccp_stat_bgwriter_buffers_checkpoint{job=~\"[[pgnodes]]\"}[5m])",
     "legendFormat": "CheckPoint"
    },
    {
     "expr": "irate(ccp_stat_bgwriter_buffers_clean{job=~\"[[pgnodes]]\"}[5m])",
     "legendFormat": "Clean"
    }
   ]
  },
  {
   "title": "% toward wraparound",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ccp_transaction_wraparound_percent_towards_wraparound{job=~\"[[pgnodes]]\"}"
    }
   ]
  },
  {
   "title": "% towards emergency vacuum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ccp_transaction_wraparound_percent_towards_emergency_autovac{job=~\"[[pgnodes]]\"}"
    }
   ]
  },
  {
   "title": "Total WAL Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ccp_wal_activity_total_size_bytes{job=~\"[[pgnodes]]\"}"
    }
   ]
  },
  {
   "title": "Vacuum/Analyze Activity Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ccp_stat_user_tables_autovacuum_count{job=~\"[[pgnodes]]\"}[5m]))",
     "legendFormat": "AutoVacuum"
    },
    {
     "expr": "sum(rate(ccp_stat_user_tables_autoanalyze_count{job=~\"[[pgnodes]]\"}[5m]))",
     "legendFormat": "AutoAnalyze"
    },
    {
     "expr": "sum(rate(ccp_stat_user_tables_vacuum_count{job=~\"[[pgnodes]]\"}[5m]))",
     "legendFormat": "Vacuum"
    },
    {
     "expr": "sum(rate(ccp_stat_user_tables_analyze_count{job=~\"[[pgnodes]]\"}[5m]))",
     "legendFormat": "Analyze"
    }
   ]
  }
 ]
}